# Generated by Django 4.2.27 on 2026-02-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
