# Generated by Django 4.2.27 on 2026-02-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_userprofile_referral_code_userprofile_reward_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citizenship_back',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='citizenship_front',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='income_proof',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selfie',
            field=models.FileField(blank=True, null=True, upload_to='kyc_docs/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
