# Generated by Django 4.2.27 on 2026-03-12 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0005_userprofile_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytransaction',
            name='khalti_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moneytransaction',
            name='khalti_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moneytransaction',
            name='payment_status',
            field=models.CharField(default='NOT_PAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='goodsexchange',
            name='exchange_type',
            field=models.CharField(choices=[('LEND', 'Lend'), ('BORROW', 'Borrow'), ('EXCHANGE', 'Swap/Exchange'), ('RENT', 'Rent (Small Fee)')], max_length=20),
        ),
        migrations.CreateModel(
            name='TrustScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('reason', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
