# Generated by Django 4.2.27 on 2026-03-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_signupotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
    ]
